<%
set strings("fr") = server.createobject("scripting.dictionary")
strings("fr")("ok") = "OK"
strings("fr")("home") = "accueil"
strings("fr")("back") = "retour"
strings("fr")("create") = "ajouter "
strings("fr")("delete") = "supprimer "
strings("fr")("edit") = "modifier "
strings("fr")("list") = "liste "
strings("fr")("details") = "voir "
strings("fr")("cancel") = "annuler"
strings("fr")("choose") = "choisir"
strings("fr")("all") = "tous"
strings("fr")("dashboard") = "Tableau de bord"
strings("fr")("doyouconfirmdelete") = "Confirmez-vous la suppression de cet enregistrement ?"
strings("fr")("confirmdelete") = "Supprimer cet enregistrement ?"
strings("fr")("login_error_ip") = "Votre IP n'est pas autorisée, veuillez contacter l'administrateur de votre application"
strings("fr")("login_error_credentials") = "Vos identifiants sont incorrects, veuillez contacter l'administrateur de votre application"
strings("fr")("notcommunicated") = "NC"
%>
<%
set strings("en") = server.createobject("scripting.dictionary")
strings("en")("ok") = "OK"
strings("en")("home") = "home"
strings("en")("back") = "back"
strings("en")("create") = "create "
strings("en")("delete") = "delete "
strings("en")("edit") = "edit "
strings("en")("list") = "list "
strings("en")("details") = "view "
strings("en")("cancel") = "cancel"
strings("en")("choose") = "choose"
strings("en")("all") = "all"
strings("en")("dashboard") = "Dashboard"
strings("en")("doyouconfirmdelete") = "Confirm delete ?"
strings("en")("confirmdelete") = "delete"
strings("en")("login_error_ip") = "Your IP is not allowed, please contact the administrator of your application"
strings("en")("login_error_credentials") = "Your credentials are incorrect, please contact your app administrator"
strings("en")("notcommunicated") = "NC"
%>