<%
set strings("fr") = server.createobject("scripting.dictionary")
strings("fr")("ok") = "OK"
strings("fr")("home") = "accueil"
strings("fr")("back") = "retour"
strings("fr")("create") = "ajouter "
strings("fr")("delete") = "supprimer "
strings("fr")("edit") = "modifier "
strings("fr")("list") = "liste "
strings("fr")("details") = "voir "
strings("fr")("cancel") = "annuler"
strings("fr")("choose") = "choisir"
strings("fr")("all") = "tous"
strings("fr")("dashboard") = "Tableau de bord"
strings("fr")("doyouconfirmdelete") = "Confirmez-vous la suppression de cet enregistrement ?"
strings("fr")("confirmdelete") = "Supprimer cet enregistrement ?"
strings("fr")("login_error_ip") = "Votre IP n'est pas autorisée, veuillez contacter l'administrateur de votre application"
strings("fr")("login_error_credentials") = "Vos identifiants sont incorrects, veuillez contacter l'administrateur de votre application"
strings("fr")("notcommunicated") = "NC"
strings("fr")("mespreferences") = "Mes préférences"
strings("fr")("contacterlesupport") = "Contacter le support"
strings("fr")("sedeconnecter") = "Se déconnecter"
strings("fr")("seconnecter") = "Se connecter" 
strings("fr")("resetpass") = "Rénitialiser votre mot de passe"
strings("fr")("tableaudebord") = "Tableau de bord"
strings("fr")("Changermotdepasse") = "Changer mot de passe"
strings("fr")("logwithloginerror") = "Identifiants incorrects. Merci de vérifier vos login et mot de passe."
strings("fr")("utilisateur_email_errormessage") = "Cette adresse mail est déjà utilisée"
strings("fr")("utilisateur_motdepasse_errormessage") = "Le mot de passe est incorrect"
strings("fr")("logwithemailerror") = "Veuillez vérifier vos identifiants"
strings("fr")("txterrorconfirmip") = "Le code de confirmation est invalide"
strings("fr")("txterrorconfirmip") = "Accès non autorisé"
strings("fr")("profile") = "Profile"
strings("fr")("utilisateur_motdepasse_confirmation") = "Confirmer le mot de passe"
strings("fr")("erreurmdp") = "Les mots de passe doivent être identique"
strings("fr")("changementmdpok") = "Le mot de passe a été changé avec succés"
    
%>
